name: leafcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.4
  lucide_icons: ^0.257.0
  flutter_bloc: ^9.1.0
  image_picker: ^1.1.2
  equatable: ^2.0.7
  google_sign_in: ^6.2.2
  http: ^1.3.0
  # tflite_flutter: ^0.11.0
  image: ^4.5.3
  flutter_launcher_icons: ^0.14.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  intl: ^0.20.2
  pdf: ^3.11.3
  open_file: ^3.5.10
  printing: ^5.14.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/model/
    - assets/json/
    - assets/diseases/
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
